@id = 1
@email = asdf@asdf.com


### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "asdf"
}

### Sign in as an existing user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "asdf"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID 
GET http://localhost:3000/auth/{{id}}

### Find all users with a given email
GET http://localhost:3000/auth?email={{email}}

### Delete a user with a given id
DELETE http://localhost:3000/auth/{{id}}

### Update a user with a given id
PATCH http://localhost:3000/auth/{{id}}
Content-Type: application/json

{
    "email": "aaa@aaa.com"
}